name: SkyGridSupport
version: '${project.version}'
main: com.skygridsupport.SkyGridSupport
api-version: '1.20'
softdepend:
  - GriefPrevention
  - WorldGuard

commands:
  gridrtp:
    description: Randomly teleport in the skygrid.